// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW2Oy3E_640KLWckRwr_sRZr-QKpRZI98',
    appId: '1:523779757326:web:b4c76cca0090538639f35f',
    messagingSenderId: '523779757326',
    projectId: 'maychat-7fa35',
    authDomain: 'maychat-7fa35.firebaseapp.com',
    storageBucket: 'maychat-7fa35.firebasestorage.app',
    measurementId: 'G-8W7J57EDVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2GCKIyaWkPhYSOTGWuPmBHKuYDBXTYtg',
    appId: '1:523779757326:android:6e43a8709ad1fc7839f35f',
    messagingSenderId: '523779757326',
    projectId: 'maychat-7fa35',
    storageBucket: 'maychat-7fa35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3YAFkmolbUpSG8iZuj6hQRBaxw58odwI',
    appId: '1:523779757326:ios:865725bed880c61d39f35f',
    messagingSenderId: '523779757326',
    projectId: 'maychat-7fa35',
    storageBucket: 'maychat-7fa35.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3YAFkmolbUpSG8iZuj6hQRBaxw58odwI',
    appId: '1:523779757326:ios:865725bed880c61d39f35f',
    messagingSenderId: '523779757326',
    projectId: 'maychat-7fa35',
    storageBucket: 'maychat-7fa35.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW2Oy3E_640KLWckRwr_sRZr-QKpRZI98',
    appId: '1:523779757326:web:bc9128a4832d2c0739f35f',
    messagingSenderId: '523779757326',
    projectId: 'maychat-7fa35',
    authDomain: 'maychat-7fa35.firebaseapp.com',
    storageBucket: 'maychat-7fa35.firebasestorage.app',
    measurementId: 'G-S52FNGCCJV',
  );
}
